const express = require("express");
const router = express.Router();
const PDFDocument = require("pdfkit");

const db = require("../db").promise();

/**
 * ======================================
 * HELPER → GET RATINGS
 * ======================================
 */
async function getRatingsData() {
  const [rows] = await db.query(`
    SELECT rating, COUNT(*) AS count
    FROM session
    WHERE rating IS NOT NULL
    GROUP BY rating
  `);

  const ratings = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
  let totalRatings = 0;

  rows.forEach((row) => {
    ratings[row.rating] = row.count;
    totalRatings += row.count;
  });

  return { totalRatings, ratings };
}

/**
 * ======================================
 * HELPER → GET INTERACTIONS
 * ======================================
 */
async function getInteractionData() {
  const [rows] = await db.query(`
    SELECT summary_text AS site, COUNT(*) AS interaction_count
    FROM session_summary
    GROUP BY summary_text
  `);

  const result = {
    "Thuparamaya Dagaba": 0,
    "Sandakada Pahana": 0,
    "Muragala": 0,
    "Monastic Hospital Ruins": 0,
  };

  rows.forEach((row) => {
    if (result.hasOwnProperty(row.site)) {
      result[row.site] = row.interaction_count;
    }
  });

  return result;
}

/**
 * ============================
 * RATINGS JSON
 * ============================
 */
router.get("/ratings", async (req, res) => {
  try {
    const data = await getRatingsData();
    res.json(data);
  } catch (err) {
    console.error("RATINGS ERROR:", err);
    res.status(500).json({ message: "Failed" });
  }
});

/**
 * ============================
 * INTERACTIONS JSON
 * ============================
 */
router.get("/interactions", async (req, res) => {
  try {
    const interactions = await getInteractionData();
    res.json({ interactions });
  } catch (err) {
    console.error("INTERACTIONS ERROR:", err);
    res.status(500).json({ message: "Failed" });
  }
});

/**
 * ============================
 * EXPORT PDF
 * ============================
 */
router.get("/pdf", async (req, res) => {
  try {
    const { totalRatings, ratings } = await getRatingsData();
    const interactions = await getInteractionData();

    const doc = new PDFDocument({ margin: 40 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=visitor_analytics.pdf"
    );

    doc.pipe(res);

    // ======================
    // TITLE
    // ======================
    doc.fontSize(20).text("HeritXR Visitor Analytics Report", {
      align: "center",
    });

    doc.moveDown();
    doc.fontSize(12).text(`Generated: ${new Date().toLocaleString()}`);

    doc.moveDown().moveDown();

    // ======================
    // RATINGS
    // ======================
    doc.fontSize(16).text("Ratings Summary");
    doc.moveDown(0.5);

    doc.fontSize(12);
    doc.text(`Total Rated Visitors : ${totalRatings}`);
    doc.text(`1 Star : ${ratings[1]}`);
    doc.text(`2 Stars : ${ratings[2]}`);
    doc.text(`3 Stars : ${ratings[3]}`);
    doc.text(`4 Stars : ${ratings[4]}`);
    doc.text(`5 Stars : ${ratings[5]}`);

    doc.moveDown().moveDown();

    // ======================
    // INTERACTIONS
    // ======================
    doc.fontSize(16).text("Artifact Interactions");
    doc.moveDown(0.5);

    doc.fontSize(12);
    Object.entries(interactions).forEach(([site, count]) => {
      doc.text(`${site} : ${count}`);
    });

    doc.moveDown().moveDown();

    doc.text("Generated by HeritXR System", { align: "center" });

    doc.end();

    console.log("📄 PDF REPORT GENERATED");
  } catch (err) {
    console.error("PDF ERROR:", err);
    res.status(500).json({ message: "Failed to generate PDF" });
  }
});

module.exports = router;
